### ISSUE TITLE
unRaid 6.8.3 版本正在更新吗？

### ISSUE THREAD

**Issue by aysun168** [KleinerSource/unRAID-chs-project#1]
感谢做出的贡献，unRaid 6.8.3 版本会更新吗？
unRaid 6.8.3 版本可以用unRaid 6.8.2 版本的汉化包吗?

**Comment by KleinerSource** [comment]
> 感谢做出的贡献，unRaid 6.8.3 版本会更新吗？
> 
> unRaid 6.8.3 版本可以用unRaid 6.8.2 版本的汉化包吗?

抱歉 目前没有做6.8.3的计划 因为本人并没有正版软件 无法正常调试翻译所带来的bug
理论上 682和683 多多少少会有些不兼容的地方 不够大部分内容是支持的 有能力的话可以自行i去683版本的 web文件 使用软件去比较差异。来自制汉化

**Comment by iMaxson** [comment]
> > 感谢做出的贡献，unRaid 6.8.3 版本会更新吗？
> > unRaid 6.8.3 版本可以用unRaid 6.8.2 版本的汉化包吗?
> 
> 抱歉 目前没有做6.8.3的计划 因为本人并没有正版软件 无法正常调试翻译所带来的bug
> 理论上 682和683 多多少少会有些不兼容的地方 不过大部分内容是支持的 有能力的话可以自行提取683版本的 web文件 使用软件去比较差异。来自制汉化
你做汉化应该可以让官方给你一个正版的！

**Comment by iMaxson** [comment]
老大给官方电邮让他们给你个正版啊。把你github的网址附上，应该没问题的。
